example_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hordak.urls", namespace="hordak")),
]

hordak/urls.py
from django.urls import path

from hordak.views import accounts, statement_csv_import, transactions


app_name = "hordak"

urlpatterns = [
    path(
        "transactions/create/",
        transactions.TransactionCreateView.as_view(),
        name="transactions_create",
    ),
    path(
        "transactions/<str:uuid>/delete/",
        transactions.TransactionDeleteView.as_view(),
        name="transactions_delete",
    ),
    path(
        "transactions/currency/",
        transactions.CurrencyTradeView.as_view(),
        name="currency_trade",
    ),
    path(
        "transactions/reconcile/",
        transactions.TransactionsReconcileView.as_view(),
        name="transactions_reconcile",
    ),
    path(
        "transactions/list/",
        transactions.TransactionsListView.as_view(),
        name="transactions_list",
    ),
    path("transactions/legs/", transactions.LegsListView.as_view(), name="legs_list"),
    path(
        "statement-line/<str:uuid>/unreconcile/",
        transactions.UnreconcileView.as_view(),
        name="transactions_unreconcile",
    ),
    path("", accounts.AccountListView.as_view(), name="accounts_list"),
    path(
        "accounts/create/", accounts.AccountCreateView.as_view(), name="accounts_create"
    ),
    path(
        "accounts/update/<str:uuid>/",
        accounts.AccountUpdateView.as_view(),
        name="accounts_update",
    ),
    path(
        "accounts/<str:uuid>/",
        accounts.AccountTransactionsView.as_view(),
        name="accounts_transactions",
    ),
    path(
        "import/", statement_csv_import.CreateImportView.as_view(), name="import_create"
    ),
    path(
        "import/<str:uuid>/setup/",
        statement_csv_import.SetupImportView.as_view(),
        name="import_setup",
    ),
    path(
        "import/<str:uuid>/dry-run/",
        statement_csv_import.DryRunImportView.as_view(),
        name="import_dry_run",
    ),
    path(
        "import/<str:uuid>/run/",
        statement_csv_import.ExecuteImportView.as_view(),
        name="import_execute",
    ),
]

hordak/forms/statement_csv_import.py
from django import forms
from django.forms import inlineformset_factory

from hordak.models import (
    Account,
    StatementImport,
    TransactionCsvImport,
    TransactionCsvImportColumn,
)


class TransactionCsvImportForm(forms.ModelForm):
    bank_account = forms.ModelChoiceField(
        Account.objects.filter(is_bank_account=True), label="Import data for account"
    )

    class Meta:
        model = TransactionCsvImport
        fields = ("has_headings", "file")

    def save(self, commit=True):
        exists = bool(self.instance.pk)
        self.instance.hordak_import = StatementImport.objects.create(
            bank_account=self.cleaned_data["bank_account"], source="csv"
        )
        obj = super(TransactionCsvImportForm, self).save()
        if not exists:
            obj.create_columns()
        return obj


class TransactionCsvImportColumnForm(forms.ModelForm):
    class Meta:
        model = TransactionCsvImportColumn
        fields = ("to_field",)


TransactionCsvImportColumnFormSet = inlineformset_factory(
    parent_model=TransactionCsvImport,
    model=TransactionCsvImportColumn,
    form=TransactionCsvImportColumnForm,
    extra=0,
    can_delete=False,
)

hordak/views/accounts.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from hordak.forms import accounts as account_forms
from hordak.models import Account, Leg


class AccountListView(LoginRequiredMixin, ListView):
    """View for listing accounts

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^accounts/$', AccountListView.as_view(), name='accounts_list'),
            ]

    """

    model = Account
    template_name = "hordak/accounts/account_list.html"
    context_object_name = "accounts"


class AccountCreateView(LoginRequiredMixin, CreateView):
    """View for creating accounts

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^accounts/create/$',
                    AccountCreateView.as_view(success_url=reverse_lazy('accounts_list')),
                    name='accounts_create'),
            ]

    """

    form_class = account_forms.AccountForm
    template_name = "hordak/accounts/account_create.html"
    success_url = reverse_lazy("hordak:accounts_list")


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    """View for updating accounts

    Note that :class:`hordak.forms.AccountForm` prevents updating of the ``currency``
    and ``type`` fields. Also note that this view expects to receive the Account's
    ``uuid`` field in the URL (see example below).

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^accounts/update/(?P<uuid>.+)/$',
                    AccountUpdateView.as_view(success_url=reverse_lazy('accounts_list')),
                    name='accounts_update'),
            ]

    """

    model = Account
    form_class = account_forms.AccountForm
    template_name = "hordak/accounts/account_update.html"
    slug_field = "uuid"
    slug_url_kwarg = "uuid"
    context_object_name = "account"
    success_url = reverse_lazy("hordak:accounts_list")


# TODO: remove ignore comment once https://github.com/typeddjango/django-stubs/issues/873 is fixed
class AccountTransactionsView(LoginRequiredMixin, SingleObjectMixin, ListView):  # type: ignore
    template_name = "hordak/accounts/account_transactions.html"
    model = Leg
    slug_field = "uuid"
    slug_url_kwarg = "uuid"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(AccountTransactionsView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = Account.objects.all()
        return super(AccountTransactionsView, self).get_object(queryset)

    def get_context_object_name(self, obj):
        return "legs" if hasattr(obj, "__iter__") else "account"

    def get_queryset(self):
        queryset = super(AccountTransactionsView, self).get_queryset()
        queryset = (
            Leg.objects.filter(account=self.object)
            .order_by("-transaction__date", "-pk")
            .select_related("transaction")
        )
        return queryset

hordak/views/statement_csv_import.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView

from hordak.forms.statement_csv_import import (
    TransactionCsvImportColumnFormSet,
    TransactionCsvImportForm,
)
from hordak.models import TransactionCsvImport
from hordak.resources import StatementLineResource


class CreateImportView(LoginRequiredMixin, CreateView):
    model = TransactionCsvImport
    form_class = TransactionCsvImportForm
    template_name = "hordak/statement_import/import_create.html"

    def get_success_url(self):
        return reverse("hordak:import_setup", args=[self.object.uuid])


class SetupImportView(LoginRequiredMixin, UpdateView):
    """View for setting up of the import process

    This involves mapping columns to import fields, and collecting
    the date format
    """

    context_object_name = "transaction_import"
    slug_url_kwarg = "uuid"
    slug_field = "uuid"
    model = TransactionCsvImport
    fields = ("date_format",)
    template_name = "hordak/statement_import/import_setup.html"

    def get_context_data(self, **kwargs):
        context = super(SetupImportView, self).get_context_data(**kwargs)
        context["formset"] = TransactionCsvImportColumnFormSet(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form_class()(request.POST, request.FILES, instance=self.object)
        formset = TransactionCsvImportColumnFormSet(request.POST, instance=self.object)

        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def get_success_url(self):
        return reverse("hordak:import_dry_run", args=[self.object.uuid])


class AbstractImportView(LoginRequiredMixin, DetailView):
    context_object_name = "transaction_import"
    slug_url_kwarg = "uuid"
    slug_field = "uuid"
    model = TransactionCsvImport
    dry_run = True

    def get(self, request, **kwargs):
        return super(AbstractImportView, self).get(request, **kwargs)

    def post(self, request, **kwargs):
        transaction_import = self.get_object()
        resource = StatementLineResource(
            date_format=transaction_import.date_format,
            statement_import=transaction_import.hordak_import,
        )

        self.result = resource.import_data(
            dataset=transaction_import.get_dataset(),
            dry_run=self.dry_run,
            use_transactions=True,
            collect_failed_rows=True,
        )
        return self.get(request, **kwargs)

    def get_context_data(self, **kwargs):
        return super(AbstractImportView, self).get_context_data(
            result=getattr(self, "result", None), **kwargs
        )


class DryRunImportView(AbstractImportView):
    template_name = "hordak/statement_import/import_dry_run.html"
    dry_run = True


class ExecuteImportView(AbstractImportView):
    template_name = "hordak/statement_import/import_execute.html"
    dry_run = False

hordak/views/transactions.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction as db_transaction
from django.http import Http404
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView

from hordak.forms import LegFormSet, SimpleTransactionForm, TransactionForm
from hordak.forms.transactions import CurrencyTradeForm
from hordak.models import Leg, StatementLine, Transaction


class TransactionCreateView(LoginRequiredMixin, CreateView):
    """View for creation of simple transactions.

    This functionality is provided by :class:`hordak.models.Account.transfer_to()`,
    see the method's documentation for additional details.

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^transactions/create/$', TransactionCreateView.as_view(), name='transactions_create'),
            ]
    """

    form_class = SimpleTransactionForm
    success_url = reverse_lazy("hordak:accounts_list")
    template_name = "hordak/transactions/transaction_create.html"


class CurrencyTradeView(LoginRequiredMixin, CreateView):
    form_class = CurrencyTradeForm
    success_url = reverse_lazy("hordak:accounts_list")
    template_name = "hordak/transactions/currency_trade.html"

    def get_form_kwargs(self):
        kwargs = super(CurrencyTradeView, self).get_form_kwargs()
        kwargs.pop("instance")
        return kwargs


class TransactionsListView(LoginRequiredMixin, ListView):
    """View for listing transactions"""

    model = Transaction
    template_name = "hordak/transactions/transaction_list.html"
    context_object_name = "transactions"
    ordering = ["-date", "-pk"]


class LegsListView(LoginRequiredMixin, ListView):
    """View for listing legs"""

    model = Leg
    template_name = "hordak/transactions/leg_list.html"
    context_object_name = "legs"
    ordering = ["-transaction__date", "-transaction__pk", "-pk"]


class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    slug_url_kwarg = "uuid"
    slug_field = "uuid"
    template_name = "hordak/transactions/transaction_delete.html"
    context_object_name = "transaction"
    success_url = reverse_lazy("hordak:accounts_list")


class TransactionsReconcileView(LoginRequiredMixin, ListView):
    """Handle rendering and processing in the reconciliation view

    Note that this only extends ListView, and we implement the form
    processing functionality manually.

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^transactions/reconcile/$',
                    TransactionsReconcileView.as_view(), name='transactions_reconcile'),
            ]
    """

    template_name = "hordak/transactions/reconcile.html"
    model = StatementLine
    paginate_by = 50
    context_object_name = "statement_lines"
    ordering = ["-date", "-pk"]
    success_url = reverse_lazy("hordak:accounts_list")

    def get_uuid(self):
        return self.request.POST.get("reconcile") or self.request.GET.get("reconcile")

    def get_object(self, queryset=None):
        # Get any Statement Line instance that was specified
        if queryset is None:
            queryset = self.get_queryset()

        uuid = self.get_uuid()
        if not uuid:
            return None

        queryset = queryset.filter(uuid=uuid, transaction=None)
        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404("No unreconciled statement line found for {}".format(uuid))

        return obj

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(TransactionsReconcileView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        # Make sure the ListView gets setup
        self.get(self.request, *self.args, **self.kwargs)

        # Check form validity
        transaction_form = self.get_transaction_form()
        leg_formset = self.get_leg_formset()

        if transaction_form.is_valid() and leg_formset.is_valid():
            return self.form_valid(transaction_form, leg_formset)
        else:
            return self.form_invalid(transaction_form, leg_formset)

    def form_valid(self, transaction_form, leg_formset):
        with db_transaction.atomic():
            # Save the transaction
            transaction_form.instance.date = self.object.date
            transaction = transaction_form.save()

            # Create the inbound transaction leg
            bank_account = self.object.statement_import.bank_account
            amount = self.object.amount * -1
            Leg.objects.create(
                transaction=transaction,
                account=bank_account,
                amount=amount,
                # Note that bank accounts can only have one currency
                amount_currency=bank_account.currencies[0],
            )

            # We need to create a new leg formset in order to pass in the
            # transaction we just created (required as the new legs must
            # be associated with the new transaction)
            leg_formset = self.get_leg_formset(instance=transaction)
            assert leg_formset.is_valid()
            leg_formset.save()

            # Now point the statement line to the new transaction
            self.object.transaction = transaction
            self.object.save()

        self.object = None
        return self.render_to_response(self.get_context_data())

    def form_invalid(self, transaction_form, leg_formset):
        return self.render_to_response(
            self.get_context_data(
                transaction_form=transaction_form, leg_formset=leg_formset
            )
        )

    def get_context_data(self, **kwargs):
        # If a Statement Line has been selected for reconciliation,
        # then add the forms to the context
        if self.object:
            kwargs.update(
                transaction_form=self.get_transaction_form(),
                leg_formset=self.get_leg_formset(),
                reconcile_line=self.object,
            )
        return super(TransactionsReconcileView, self).get_context_data(**kwargs)

    def get_transaction_form(self):
        return TransactionForm(
            data=self.request.POST or None,
            initial=dict(description=self.object.description),
        )

    def get_leg_formset(self, **kwargs):
        return LegFormSet(
            data=self.request.POST or None, statement_line=self.object, **kwargs
        )


class UnreconcileView(LoginRequiredMixin, View):
    def post(self, request, uuid):
        statement_line = get_object_or_404(StatementLine, uuid=uuid)
        statement_line.transaction.delete()
        return HttpResponseRedirect(reverse("hordak:transactions_reconcile"))

hordak/templates/hordak/accounts/account_create.html
{% extends 'hordak/base.html' %}

{% block page_name %}Create account{% endblock %}
{% block page_description %}Create a new account{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% include 'hordak/partials/form.html' with form=form %}

        <p>
            <input type="submit" class="btn btn-primary btn-lg pull-right" value="Create account">
            <a href="{% url 'hordak:accounts_list' %}">Cancel</a>
        </p>
    </form>
{% endblock %}

hordak/templates/hordak/accounts/account_list.html
{% extends 'hordak/base.html' %}

{% block page_name %}Accounts{% endblock %}
{% block page_description %}See all accounts at a glance{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Entity</th>
                <th>Name</th>
                <th>Type</th>
                <th>Balance</th>
                <th>Currencies</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{{ account.entity.name }}</td>
                <td>
                    <div style="padding-left: {% widthratio account.get_level 1 15 %}px;">
                        {% if account.is_child_node %}↳{% endif %}
                        {{ account.name }}
                    </div>
                </td>
                <td>{{ account.get__type_display }}</td>
                <td>{{ account.balance }}</td>
                <td>{{ account.currencies|join:', ' }}</td>
                <td>
                    {% if account.is_leaf_node %}
                        <a href="{% url 'hordak:accounts_transactions' account.uuid %}" class="btn btn-default btn-xs">Transactions</a>
                    {% else %}
                    <a href="{% url 'hordak:accounts_transactions' account.uuid %}" class="btn btn-default btn-xs">Parent</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'hordak:accounts_update' account.uuid %}" class="btn btn-default btn-xs">Edit</a>
                </td>
            </tr>
            {% empty %}
                <tr>
                <td colspan="6" class="text-center">No accounts exist</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

hordak/templates/hordak/accounts/account_transactions.html
{% extends 'hordak/base.html' %}
{% load hordak %}

{% block page_name %}Account {{ account.name }}{% endblock %}
{% block page_description %}See all transactions for an account{% endblock %}

{% block content %}
    <h5>Balance: {{ account.balance }}</h5>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Date</th>
                <th>Account</th>
                <th>Description</th>
                <th>Debit</th>
                <th>Credit</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            {% for leg in legs %}
                <tr>
                    <td>{{ leg.transaction.date }}</td>
                    <td>
                        {% if leg.is_debit %}
                            {% for debit_leg in leg.transaction.legs.debits %}
                                {{ debit_leg.account.name }}{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        {% else %}
                            {% for credit_leg in leg.transaction.legs.credits %}
                                {{ credit_leg.account.name }}{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ leg.transaction.description }}</td>
                    <td>{% if leg.is_debit %}{{ leg.amount|abs }}{% endif %}</td>
                    <td>{% if leg.is_credit %}{{ leg.amount|abs }}{% endif %}</td>
                    <td>{{ leg.account_balance_after }}</td>
                    <td>
                        <a href="{% url 'hordak:transactions_delete' leg.transaction.uuid %}" class="btn btn-xs btn-danger">Delete</a>
                    </td>
                </tr>

                {# Show the entering balance at the bottom of the list #}
                {% if forloop.last %}
                    <tr>
                        <td colspan="5"></td>
                        <td>{{ leg.account_balance_before }}</td>
                    </tr>
                {% endif %}
            {% empty %}
                <tr>
                <td colspan="6" class="text-center">No transactions exist</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <p>
        <a href="{% url 'hordak:accounts_list' %}">Back</a>
    </p>
{% endblock %}

hordak/templates/hordak/accounts/account_update.html
{% extends 'hordak/base.html' %}

{% block page_name %}Edit account{% endblock %}
{% block page_description %}Create a new account{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label class="control-label">Type</label>
            <div class="form-control-static">{{ account.get__type_display }}</div>
        </div>

        <div class="form-group">
            <label class="control-label">Currencies</label>
            <div class="form-control-static">{{ account.currencies|join:', ' }}</div>
        </div>

        {% include 'hordak/partials/form.html' with form=form %}

        <p>
            <input type="submit" class="btn btn-primary btn-lg pull-right" value="Save changes">
            <a href="{% url 'hordak:accounts_list' %}">Cancel</a>
        </p>
    </form>

{% endblock %}