example_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hordak.urls", namespace="hordak")),
]

hordak/urls.py
from django.urls import path

from hordak.views import accounts, statement_csv_import, transactions


app_name = "hordak"

urlpatterns = [
    path(
        "transactions/create/",
        transactions.TransactionCreateView.as_view(),
        name="transactions_create",
    ),
    path(
        "transactions/<str:uuid>/delete/",
        transactions.TransactionDeleteView.as_view(),
        name="transactions_delete",
    ),
    path(
        "transactions/currency/",
        transactions.CurrencyTradeView.as_view(),
        name="currency_trade",
    ),
    path(
        "transactions/reconcile/",
        transactions.TransactionsReconcileView.as_view(),
        name="transactions_reconcile",
    ),
    path(
        "transactions/list/",
        transactions.TransactionsListView.as_view(),
        name="transactions_list",
    ),
    path("transactions/legs/", transactions.LegsListView.as_view(), name="legs_list"),
    path(
        "statement-line/<str:uuid>/unreconcile/",
        transactions.UnreconcileView.as_view(),
        name="transactions_unreconcile",
    ),
    path("", accounts.AccountListView.as_view(), name="accounts_list"),
    path(
        "accounts/create/", accounts.AccountCreateView.as_view(), name="accounts_create"
    ),
    path(
        "accounts/update/<str:uuid>/",
        accounts.AccountUpdateView.as_view(),
        name="accounts_update",
    ),
    path(
        "accounts/<str:uuid>/",
        accounts.AccountTransactionsView.as_view(),
        name="accounts_transactions",
    ),
    path(
        "import/", statement_csv_import.CreateImportView.as_view(), name="import_create"
    ),
    path(
        "import/<str:uuid>/setup/",
        statement_csv_import.SetupImportView.as_view(),
        name="import_setup",
    ),
    path(
        "import/<str:uuid>/dry-run/",
        statement_csv_import.DryRunImportView.as_view(),
        name="import_dry_run",
    ),
    path(
        "import/<str:uuid>/run/",
        statement_csv_import.ExecuteImportView.as_view(),
        name="import_execute",
    ),
]

hordak/forms/statement_csv_import.py
from django import forms
from django.forms import inlineformset_factory

from hordak.models import (
    Account,
    StatementImport,
    TransactionCsvImport,
    TransactionCsvImportColumn,
)


class TransactionCsvImportForm(forms.ModelForm):
    bank_account = forms.ModelChoiceField(
        Account.objects.filter(is_bank_account=True), label="Import data for account"
    )

    class Meta:
        model = TransactionCsvImport
        fields = ("has_headings", "file")

    def save(self, commit=True):
        exists = bool(self.instance.pk)
        self.instance.hordak_import = StatementImport.objects.create(
            bank_account=self.cleaned_data["bank_account"], source="csv"
        )
        obj = super(TransactionCsvImportForm, self).save()
        if not exists:
            obj.create_columns()
        return obj


class TransactionCsvImportColumnForm(forms.ModelForm):
    class Meta:
        model = TransactionCsvImportColumn
        fields = ("to_field",)


TransactionCsvImportColumnFormSet = inlineformset_factory(
    parent_model=TransactionCsvImport,
    model=TransactionCsvImportColumn,
    form=TransactionCsvImportColumnForm,
    extra=0,
    can_delete=False,
)

hordak/views/accounts.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from hordak.forms import accounts as account_forms
from hordak.models import Account, Leg


class AccountListView(LoginRequiredMixin, ListView):
    """View for listing accounts

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^accounts/$', AccountListView.as_view(), name='accounts_list'),
            ]

    """

    model = Account
    template_name = "hordak/accounts/account_list.html"
    context_object_name = "accounts"


class AccountCreateView(LoginRequiredMixin, CreateView):
    """View for creating accounts

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^accounts/create/$',
                    AccountCreateView.as_view(success_url=reverse_lazy('accounts_list')),
                    name='accounts_create'),
            ]

    """

    form_class = account_forms.AccountForm
    template_name = "hordak/accounts/account_create.html"
    success_url = reverse_lazy("hordak:accounts_list")


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    """View for updating accounts

    Note that :class:`hordak.forms.AccountForm` prevents updating of the ``currency``
    and ``type`` fields. Also note that this view expects to receive the Account's
    ``uuid`` field in the URL (see example below).

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^accounts/update/(?P<uuid>.+)/$',
                    AccountUpdateView.as_view(success_url=reverse_lazy('accounts_list')),
                    name='accounts_update'),
            ]

    """

    model = Account
    form_class = account_forms.AccountForm
    template_name = "hordak/accounts/account_update.html"
    slug_field = "uuid"
    slug_url_kwarg = "uuid"
    context_object_name = "account"
    success_url = reverse_lazy("hordak:accounts_list")


# TODO: remove ignore comment once https://github.com/typeddjango/django-stubs/issues/873 is fixed
class AccountTransactionsView(LoginRequiredMixin, SingleObjectMixin, ListView):  # type: ignore
    template_name = "hordak/accounts/account_transactions.html"
    model = Leg
    slug_field = "uuid"
    slug_url_kwarg = "uuid"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(AccountTransactionsView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = Account.objects.all()
        return super(AccountTransactionsView, self).get_object(queryset)

    def get_context_object_name(self, obj):
        return "legs" if hasattr(obj, "__iter__") else "account"

    def get_queryset(self):
        queryset = super(AccountTransactionsView, self).get_queryset()
        queryset = (
            Leg.objects.filter(account=self.object)
            .order_by("-transaction__date", "-pk")
            .select_related("transaction")
        )
        return queryset

hordak/views/statement_csv_import.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView

from hordak.forms.statement_csv_import import (
    TransactionCsvImportColumnFormSet,
    TransactionCsvImportForm,
)
from hordak.models import TransactionCsvImport
from hordak.resources import StatementLineResource


class CreateImportView(LoginRequiredMixin, CreateView):
    model = TransactionCsvImport
    form_class = TransactionCsvImportForm
    template_name = "hordak/statement_import/import_create.html"

    def get_success_url(self):
        return reverse("hordak:import_setup", args=[self.object.uuid])


class SetupImportView(LoginRequiredMixin, UpdateView):
    """View for setting up of the import process

    This involves mapping columns to import fields, and collecting
    the date format
    """

    context_object_name = "transaction_import"
    slug_url_kwarg = "uuid"
    slug_field = "uuid"
    model = TransactionCsvImport
    fields = ("date_format",)
    template_name = "hordak/statement_import/import_setup.html"

    def get_context_data(self, **kwargs):
        context = super(SetupImportView, self).get_context_data(**kwargs)
        context["formset"] = TransactionCsvImportColumnFormSet(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form_class()(request.POST, request.FILES, instance=self.object)
        formset = TransactionCsvImportColumnFormSet(request.POST, instance=self.object)

        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def get_success_url(self):
        return reverse("hordak:import_dry_run", args=[self.object.uuid])


class AbstractImportView(LoginRequiredMixin, DetailView):
    context_object_name = "transaction_import"
    slug_url_kwarg = "uuid"
    slug_field = "uuid"
    model = TransactionCsvImport
    dry_run = True

    def get(self, request, **kwargs):
        return super(AbstractImportView, self).get(request, **kwargs)

    def post(self, request, **kwargs):
        transaction_import = self.get_object()
        resource = StatementLineResource(
            date_format=transaction_import.date_format,
            statement_import=transaction_import.hordak_import,
        )

        self.result = resource.import_data(
            dataset=transaction_import.get_dataset(),
            dry_run=self.dry_run,
            use_transactions=True,
            collect_failed_rows=True,
        )
        return self.get(request, **kwargs)

    def get_context_data(self, **kwargs):
        return super(AbstractImportView, self).get_context_data(
            result=getattr(self, "result", None), **kwargs
        )


class DryRunImportView(AbstractImportView):
    template_name = "hordak/statement_import/import_dry_run.html"
    dry_run = True


class ExecuteImportView(AbstractImportView):
    template_name = "hordak/statement_import/import_execute.html"
    dry_run = False

hordak/views/transactions.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction as db_transaction
from django.http import Http404
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView

from hordak.forms import LegFormSet, SimpleTransactionForm, TransactionForm
from hordak.forms.transactions import CurrencyTradeForm
from hordak.models import Leg, StatementLine, Transaction


class TransactionCreateView(LoginRequiredMixin, CreateView):
    """View for creation of simple transactions.

    This functionality is provided by :class:`hordak.models.Account.transfer_to()`,
    see the method's documentation for additional details.

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^transactions/create/$', TransactionCreateView.as_view(), name='transactions_create'),
            ]
    """

    form_class = SimpleTransactionForm
    success_url = reverse_lazy("hordak:accounts_list")
    template_name = "hordak/transactions/transaction_create.html"


class CurrencyTradeView(LoginRequiredMixin, CreateView):
    form_class = CurrencyTradeForm
    success_url = reverse_lazy("hordak:accounts_list")
    template_name = "hordak/transactions/currency_trade.html"

    def get_form_kwargs(self):
        kwargs = super(CurrencyTradeView, self).get_form_kwargs()
        kwargs.pop("instance")
        return kwargs


class TransactionsListView(LoginRequiredMixin, ListView):
    """View for listing transactions"""

    model = Transaction
    template_name = "hordak/transactions/transaction_list.html"
    context_object_name = "transactions"
    ordering = ["-date", "-pk"]


class LegsListView(LoginRequiredMixin, ListView):
    """View for listing legs"""

    model = Leg
    template_name = "hordak/transactions/leg_list.html"
    context_object_name = "legs"
    ordering = ["-transaction__date", "-transaction__pk", "-pk"]


class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    slug_url_kwarg = "uuid"
    slug_field = "uuid"
    template_name = "hordak/transactions/transaction_delete.html"
    context_object_name = "transaction"
    success_url = reverse_lazy("hordak:accounts_list")


class TransactionsReconcileView(LoginRequiredMixin, ListView):
    """Handle rendering and processing in the reconciliation view

    Note that this only extends ListView, and we implement the form
    processing functionality manually.

    Examples:

        .. code-block:: python

            urlpatterns = [
                ...
                url(r'^transactions/reconcile/$',
                    TransactionsReconcileView.as_view(), name='transactions_reconcile'),
            ]
    """

    template_name = "hordak/transactions/reconcile.html"
    model = StatementLine
    paginate_by = 50
    context_object_name = "statement_lines"
    ordering = ["-date", "-pk"]
    success_url = reverse_lazy("hordak:accounts_list")

    def get_uuid(self):
        return self.request.POST.get("reconcile") or self.request.GET.get("reconcile")

    def get_object(self, queryset=None):
        # Get any Statement Line instance that was specified
        if queryset is None:
            queryset = self.get_queryset()

        uuid = self.get_uuid()
        if not uuid:
            return None

        queryset = queryset.filter(uuid=uuid, transaction=None)
        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404("No unreconciled statement line found for {}".format(uuid))

        return obj

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(TransactionsReconcileView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        # Make sure the ListView gets setup
        self.get(self.request, *self.args, **self.kwargs)

        # Check form validity
        transaction_form = self.get_transaction_form()
        leg_formset = self.get_leg_formset()

        if transaction_form.is_valid() and leg_formset.is_valid():
            return self.form_valid(transaction_form, leg_formset)
        else:
            return self.form_invalid(transaction_form, leg_formset)

    def form_valid(self, transaction_form, leg_formset):
        with db_transaction.atomic():
            # Save the transaction
            transaction_form.instance.date = self.object.date
            transaction = transaction_form.save()

            # Create the inbound transaction leg
            bank_account = self.object.statement_import.bank_account
            amount = self.object.amount * -1
            Leg.objects.create(
                transaction=transaction,
                account=bank_account,
                amount=amount,
                # Note that bank accounts can only have one currency
                amount_currency=bank_account.currencies[0],
            )

            # We need to create a new leg formset in order to pass in the
            # transaction we just created (required as the new legs must
            # be associated with the new transaction)
            leg_formset = self.get_leg_formset(instance=transaction)
            assert leg_formset.is_valid()
            leg_formset.save()

            # Now point the statement line to the new transaction
            self.object.transaction = transaction
            self.object.save()

        self.object = None
        return self.render_to_response(self.get_context_data())

    def form_invalid(self, transaction_form, leg_formset):
        return self.render_to_response(
            self.get_context_data(
                transaction_form=transaction_form, leg_formset=leg_formset
            )
        )

    def get_context_data(self, **kwargs):
        # If a Statement Line has been selected for reconciliation,
        # then add the forms to the context
        if self.object:
            kwargs.update(
                transaction_form=self.get_transaction_form(),
                leg_formset=self.get_leg_formset(),
                reconcile_line=self.object,
            )
        return super(TransactionsReconcileView, self).get_context_data(**kwargs)

    def get_transaction_form(self):
        return TransactionForm(
            data=self.request.POST or None,
            initial=dict(description=self.object.description),
        )

    def get_leg_formset(self, **kwargs):
        return LegFormSet(
            data=self.request.POST or None, statement_line=self.object, **kwargs
        )


class UnreconcileView(LoginRequiredMixin, View):
    def post(self, request, uuid):
        statement_line = get_object_or_404(StatementLine, uuid=uuid)
        statement_line.transaction.delete()
        return HttpResponseRedirect(reverse("hordak:transactions_reconcile"))

hordak/templates/hordak/transactions/currency_trade.html
{% extends 'hordak/base.html' %}

{% block page_name %}Exchange Currency{% endblock %}
{% block page_description %}Represent the exchange of funds from one currency to another{% endblock %}

{% block content %}

    {% block notes %}
    <p>
        Currency exchanges are performed though a <em>trading account</em>. A trading account
        is unusual in that it must support multiple currencies, whereas most accounts only
        support one. The trading account has a balance in each currency it supports. If
        you convert these balances the same currency you will find your profit/loss given the
        exchange rates used.
    </p>

    <p>
        You can <a href="{% url 'hordak:accounts_create' %}">create a trading account</a>
        if you have not done so already.
    </p>
    {% endblock %}

    {% block form %}
    <form action="{% url 'hordak:currency_trade' %}" method="post">
        {% csrf_token %}
        {% block form_content %}
            {% include 'hordak/partials/form.html' with form=form %}
            <p>
                <input type="submit" value="Create Trade" class="btn btn-primary btn-lg pull-right">
                <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg pull-right">Cancel</a>
            </p>
        {% endblock %}
    </form>
    {% endblock %}

{% endblock %}

hordak/templates/hordak/transactions/leg_list.html
{% extends 'hordak/base.html' %}

{% block page_name %}Transaction Legs{% endblock %}
{% block page_description %}See all legs{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Transaction UUID</th>
                <th>Leg UUID</th>
                <th>Type</th>
                <th>Account</th>
                <th>Amount</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for leg in legs %}
            <tr>
                <td><code>{{ leg.transaction.uuid }}</code></td>
                <td><code>{{ leg.uuid }}</code></td>
                <td>{{ leg.type|title }}</td>
                <td>{{ leg.account.name }}</td>
                <td style="text-align: right;">{{ leg.amount }}</td>
                <td>{{ leg.description }}</td>
             </tr>
            {% empty %}
                <tr>
                <td colspan="6" class="text-center">No leg exist</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

hordak/templates/hordak/transactions/reconcile.html
{% extends 'hordak/base.html' %}
{% load hordak %}

{% block page_name %}Reconcile Bank Statements{% endblock %}
{% block page_description %}What did you spend money on?{% endblock %}

{% block content %}
    <table class="table table-striped">
        {% block table_header %}
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>Account</th>
                </tr>
            </thead>
        {% endblock table_header %}
        <tbody>
            {% for line in statement_lines %}
                {% block reconcile_row %}
                    <tr id="L{{ line.uuid }}">
                        <td>{{ line.date }}</td>
                        <td>{{ line.amount|color_currency }}</td>
                        <td>{{ line.description }}</td>
                        <td>
                            {% if line.transaction %}
                                <td>
                                    <dl>
                                    {% for leg in line.transaction.legs.all %}
                                        {% if leg.account != line.statement_import.bank_account %}
                                            <dt>{{ leg.account.name }}</dt>
                                            <dd>{{ leg.amount|abs }}</dd>
                                        {% endif %}
                                    {% endfor %}
                                    </dl>
                                </td>
                                <td>
                                <form action="{% url 'hordak:transactions_unreconcile' line.uuid %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Unreconcile" class="btn btn-default btn-xs">
                                </form>
                                </td>
                            {% elif line != reconcile_line %}
                                <td></td>
                                <td>
                                <form action="#L{{ line.uuid }}" method="get">
                                    <input type="hidden" name="reconcile" value="{{ line.uuid }}">
                                    <input type="hidden" name="page" value="{{ page_obj.number }}">
                                    <input type="submit" value="Reconcile" class="btn btn-primary btn-xs">
                                </form>
                                </td>
                            {% endif %}
                        </td>
                    </tr>
                {% endblock reconcile_row %}
                {% if line == reconcile_line %}
                    {% block reconcile_action_row %}
                        <tr>
                            <td colspan="4">
                                {% if leg_formset.non_form_errors %}
                                    <ul>
                                        {% for error in leg_formset.non_form_errors %}
                                        <li class="error">{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                                <form action="" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="reconcile" value="{{ line.uuid }}">
                                    <input type="hidden" name="page" value="{{ page_obj.number }}">
                                    {% block reconcile_form_content %}
                                        <table>
                                            {% block reconcile_form_content_transaction_form %}
                                                {{ transaction_form.as_div }}
                                            {% endblock %}
                                        </table>
                                        {{ leg_formset.management_form.as_div }}
                                        <table class="table table-striped">
                                            {% for form in leg_formset %}
                                                {% block leg_formset %}
                                                    <tr>
                                                        <td>{{ form.amount.as_div }}</td>
                                                        <td>{{ form.description.as_div }}</td>
                                                        <td>{{ form.account.as_div }}</td>
                                                    </tr>
                                                {% endblock %}
                                            {% endfor %}
                                        </table>

                                        <input type="submit" value="Reconcile" class="btn btn-success pull-right">
                                    {% endblock reconcile_form_content %}
                                </form>
                            </td>
                        </tr>
                    {% endblock reconcile_action_row %}
                {% endif %}
            {% empty %}
                <tr>
                    <td colspan="4">
                        {% block nothing_to_reconcile %}Nothing to reconcile, you are up to date{% endblock %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% block pagination %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endblock %}

    {% block actions %}
        <p><a href="{% url 'hordak:accounts_list' %}">Cancel</a></p>
    {% endblock %}

{% endblock %}

hordak/templates/hordak/transactions/transaction_create.html
{% extends 'hordak/base.html' %}

{% block page_name %}Create Transaction{% endblock %}
{% block page_description %}Move money between accounts{% endblock %}

{% block content %}
    <form action="{% url 'hordak:transactions_create' %}" method="post">
        {% csrf_token %}
        {% block form_content %}
            {% include 'hordak/partials/form.html' with form=form %}
            <p>
                <input type="submit" value="Create Transaction" class="btn btn-primary btn-lg pull-right">
                <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg pull-right">Cancel</a>
            </p>
        {% endblock %}
    </form>

{% endblock %}

hordak/templates/hordak/transactions/transaction_delete.html
{% extends 'hordak/base.html' %}

{% block page_name %}Delete Transaction{% endblock %}

{% block content %}
    <form action="{% url 'hordak:transactions_delete' transaction.uuid %}" method="post">
        {% csrf_token %}
        {% block form_content %}
            {% include 'hordak/partials/form.html' with form=form %}
            <div class="row">
                <div class="col-md-6 col-md-offset-3">

                    <div class="alert alert-danger alert-dismissible">
                        <h4><i class="icon fa fa-exclamation-triangle"></i> Are you sure you wish to delete this transaction?</h4>

                        <p>
                            You could alternatively create another transaction to reverse it.
                            Deleting a transaction cannot be undone.
                        </p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg">Cancel</a>
                <input type="submit" value="Confirm Deletion" class="btn btn-danger btn-lg">
            </div>
        {% endblock %}
    </form>

{% endblock %}
]

hordak/templates/hordak/transactions/transaction_list.html
{% extends 'hordak/base.html' %}

{% block page_name %}Transactions List{% endblock %}
{% block page_description %}See all transactions{% endblock %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Legs</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td valign="top"><code>{{ transaction.uuid }}</code></td>
                <td valign="top">{{ transaction.date }}</td>
                <td>
                        <dl>
                        {% for leg in transaction.legs.all %}
                          <dt>{{ leg.type|title }} <strong>{{ leg.account.name }}</strong></dt>
                          <dd style="margin: 5px 0 10px 20px; text-align: right">{{ leg.amount }}</dd>
                        {% endfor %}
                        </dl>

                </td>
                <td valign="top">{{ transaction.description }}</td>
            </tr>
            {% empty %}
                <tr>
                <td colspan="6" class="text-center">No transaction exist</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}